module.exports = ["asshole", "bastard", "bitch", "b i t c h", "b-i-t-c-h", "b_i_t_c_h", "b.i.t.c.h", "l3itch", "b!tch", "b1tch", "bi+ch", "blow job", "blowjob", "donkeyribber", "fuck", "f u c k", "f-u-c-k", "f_u_c_k", "f.u.c.k", " fuk", "fuk ", "jack-off", "jack off", "jackoff", "jerkoff", "jerk off", "jerk-off", "nigga", "nigger", " penis", "rimjob", " rim job", "shit ", "s h i t", "s-h-i-t", "s_h_i_t", "s.h.i.t", "bullshit", "horseshit", "suck di", "suck my co", "suck my di", "suck co", " vagina", "vagina ", "ma5terb8", "ma5terbate", "master-bate", "masterb8", "masterbat", "masturbat", "cunnilingus", "ejaculat", "ejakulat", "faggot", "fagot", "faggout", "faggit", "fagit", "fagout", "schlong", //strict & specific words
" 5hit ", " a55 ", " anal ", " ass ", " arse ", " boner ", " chode ", " c0ck ", " cawk ", " cock ", " cum ", " cunt ", " damn ", " dildo ", " duche ", " dyke ", " fag ", " felch ", " fellat ", " flange ", " jism ", " jizz ", " pussy ", " pussie ", " retard ", " sh!t ", " sh1t ", " shi+ ", " slut ", " tits ", " titts ", " titty", " titties", " tittie", " whore ",
" 5hit,", " a55,", " anal,", " ass,", " arse,", " boner,", " chode ", " c0ck,", " cawk,", " cock,", " cum,", " cunt,", " damn,", " dildo,", " duche,", " dyke,", " fag,", " felch,", " fellat,", " jism,", " jizz,", " pussy,", " pussie,", " retard,", " sh!t,", " sh1t,", " shi+,"," slut,", " tits,", " titts,", " whore,",
" 5hit.", " a55.", " anal.", " ass.", " arse.", " boner.", " chode ", " c0ck.", " cawk.", " cock.", " cum.", " cunt.", " damn.", " dildo.", " duche.", " dyke.", " fag.", " felch.", " fellat.", " jism.", " jizz.", " pussy.", " pussie.", " retard.", " sh!t.", " sh1t.", " shi+.", " slut.", " tits.", " titts.", " whore.",
"5hit-", "a55-", "anal-", "boner-", "chode-", "cunt-", "damn-", "dildo-", "duche-", "dyke-", "fag-", "felch-", "fellat-", "flange-", "jism-", "jizz-", "pussy-", "pussie-", "retard-", "sh!t-", "sh1t-", "shi+-", "slut-", "tits-", "titts-", "titty-", "titties-", "tittie-", "whore-",
"\n5hit ", "\na55 ", "\nanal.", "\nanal,", "\nass ", "\nass.", "\nass,", "\nass.", "\narse ", "\nboner ", "\nchode ", "\nc0ck ", "\ncawk ", "\ncok ", "\ncum ", "\ncunt ", "\ndamn", "\ndildo ", "\nduche ", "\ndyke ", "\nfag", "\nfelch ", "\nfellat ", "\njism ", "\njizz ", "\npenis ", "\npussy ", "\npussie ", "\nretard ", "\nsh!t ", "\nsh1t ","\nshi+ ", "\nslut ", "\ntits ", "\ntitts ", "\ntitty ", "\ntitties ", "\ntittie ", "\nwhore ",
" 5hit\n", " a55\n", " anal.\n", " anal,\n", " ass.\n", " ass,\n", " ass.\n", " arse\n"," boner\n", " chode\n", " c0ck\n", " cawk\n"," cock\n", " cok\n", " cum\n", " cunt\n", " damn\n", " dildo\n", " duche\n", " dyke\n", " fag\n", " felch\n", " fellat\n"," jism\n", " jizz\n", " pussy\n", " pussie\n", " retard\n", " sh!t\n", " sh1t\n", " shi+\n", "shit\n", " slut\n", " tits\n", " titts\n", " whore\n",
"\r5hit ", "\ra55 ", "\ranal. ", "\ranal, ", "\rass ", "\rass", "\rass. ", "\rass, ", "\rass. ", "\rarse. ", "\rboner ", "\rchode ", "\rc0ck ", "\rcawk ", "\rcock ", "\rcok ", "\rcum ", "\rcunt ", "\rdamn ", "\rdildo ", "\rduche ", "\rdyke ", "\rfag ", "\rfelch ", "\rfellat ", "\rfuk ", "\rjism ", "\rjizz ", "\rpenis ", "\rpussy ", "\rpussie ", "\rretard ", "\rsh!t ", "\rsh1t ", "\rshi+ ", "\rslut ", "\rtits ", "\rtitts ", "\rtitty ", "\rtitties ", "\rtittie ", "\rwhore ",
" 5hit\r", " a55\r", " ass\r", " arse\r", " boner\r", " chode\r", " c0ck\r", " cawk\r", " cock\r", " cok\r", " cum\r", " cunt\r", " damn\r", " duche\r", " dyke\r", " fag\r", " felch\r", " fellat\r", " jism\r", " jizz\r"," pussy\r", " pussie\r", " retard\r", " sh!t\r", " sh1t\r", " shi+\r", "shit\r", " slut\r", " tits\r", " titts\r", " whore\r",
"\rass-", "\nass-", " ass-", "\rcum-", "\ncum-", " cum-", "\rcock-", "\ncock-", " cock-", "\rtitty-", "\rtittie-", "\ntitty-", " \ntittie-"]; //easily hyphenated words